### ISSUE TITLE
Missing module from datasets.drop.preprocess

### ISSUE THREAD

**Issue by amritasaha87** [nitishgupta/nmn-drop#2]
Failing in test and train because of missing module datasets.drop.preprocess.

**Comment by nitishgupta** [comment]
Could you please give some more context on this?

**Comment by nitishgupta** [comment]
If you want to run something inside `datasets/drop/preprocess`, for example `tokenize.py`, from the root of this project run the command  --  `python -m datasets.drop.preprocess.tokenize`

**Comment by amritasaha87** [comment]
Oh i had pulled it a few days back and run and gotten this error and datasets/drop/preprocess was missing.. it works now!

**Comment by nitishgupta** [comment]
ah, sorry about that.
