### ISSUE TITLE
Get the operation extracted from the question only

### ISSUE THREAD

**Issue by minhson-kaist** [nitishgupta/nmn-drop#4]
Hi,
First, I want to thank you for publishing a great paper with code.
I have a question in terms of the operation. Can I get the operation results instead of the answers?
I mean the operation extracted from each question.

Thanks,

**Comment by nitishgupta** [comment]
Thank you, that you liked our paper and hopefully find the code useful.

If I understand your question correctly, you want to be able to access intermediate outputs of the modules in a program? I added this functionality in the [drop_demo_predictor](https://github.com/nitishgupta/nmn-drop/blob/master/semqa/predictors/demo_predictor.py)

The key `"program_execution"` has exactly the information you're looking for. 
```
allennlp predict \
    --output-file output.jsonl \
    --predictor drop_demo_predictor \
    --include-package semqa \
    --silent \
    --batch-size 1 \ 
    --overrides "{\"model\": { \"debug\":true}}" \
    resources/iclr_cameraready/ckpt/model.tar.gz \
    input.jsonl
```

**Comment by minhson-kaist** [comment]
Great. Thanks for your reply.
